"use client";

import { ArrowLeft, LoaderCircle, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ImageUploader } from "@/components/admin/ImageUploader";
import { createClient, type DbGallery, type DbGalleryImage } from "@/lib/supabase/client";

export default function GalleryManagePage() {
  const { id } = useParams<{ id: string }>(); const [gallery,setGallery]=useState<DbGallery|null>(null); const [images,setImages]=useState<DbGalleryImage[]>([]); const [uploads,setUploads]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  useEffect(()=>{let active=true;const client=createClient();void Promise.all([client.from("galleries").select("*").eq("id",id).single(),client.from("gallery_images").select("*").eq("gallery_id",id).order("display_order").order("created_at")]).then(([g,p])=>{if(active){setGallery(g.data as DbGallery);setImages((p.data??[]) as DbGalleryImage[]);setLoading(false);}});return()=>{active=false};},[id]);
  async function addPhotos(){if(!uploads.length)return;setSaving(true);const start=images.length;const {data,error}=await createClient().from("gallery_images").insert(uploads.map((image_url,index)=>({gallery_id:id,image_url,display_order:start+index}))).select("*");if(!error){setImages((all)=>[...all,...(data as DbGalleryImage[])]);setUploads([]);}setSaving(false);}
  async function remove(photo:DbGalleryImage){if(!window.confirm("Bu fotoğraf albümden silinsin mi?"))return;const {error}=await createClient().from("gallery_images").delete().eq("id",photo.id);if(!error)setImages((all)=>all.filter((x)=>x.id!==photo.id));}
  async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=images.length)return;const next=[...images];[next[index],next[target]]=[next[target],next[index]];setImages(next);await Promise.all(next.map((photo,display_order)=>createClient().from("gallery_images").update({display_order}).eq("id",photo.id)));}
  if(loading)return <p className="flex items-center gap-2"><LoaderCircle className="size-5 animate-spin"/>Yükleniyor…</p>; if(!gallery)return <p>Albüm bulunamadı.</p>;
  return <div className="space-y-6"><div><Link href="/admin/galeri" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="size-4"/>Albümlere dön</Link><h1 className="mt-4 text-2xl font-bold">{gallery.title}</h1><p className="mt-1 text-sm text-slate-600">Fotoğrafları tek tek yönetin ve sıralayın.</p></div><section className="rounded-xl border bg-white p-5 shadow-sm"><ImageUploader value={uploads} onChange={setUploads} label="Yeni fotoğraflar" multiple/><button type="button" disabled={saving||!uploads.length} onClick={()=>void addPhotos()} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-md bg-red-600 px-4 font-semibold text-white disabled:opacity-50"><Save className="size-4"/>Fotoğrafları Albüme Ekle</button></section><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{images.map((photo,index)=><article key={photo.id} className="overflow-hidden rounded-xl border bg-white"><div className="aspect-video bg-cover bg-center" style={{backgroundImage:`url(${photo.image_url})`}}/><div className="flex items-center justify-between p-3"><div className="flex gap-1"><button onClick={()=>void move(index,-1)} disabled={index===0} className="rounded border px-2 py-1 text-xs disabled:opacity-30">←</button><button onClick={()=>void move(index,1)} disabled={index===images.length-1} className="rounded border px-2 py-1 text-xs disabled:opacity-30">→</button></div><button onClick={()=>void remove(photo)} className="inline-flex items-center gap-1 text-xs font-semibold text-red-700"><Trash2 className="size-4"/>Fotoğrafı Sil</button></div></article>)}</div></div>;
}
