"use client";

import { Eye, EyeOff, LoaderCircle, Trash2 } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient, formatTurkishDate } from "@/lib/supabase/client";

type Message = { id: string; name: string; email: string; phone: string | null; subject: string | null; message: string; is_read: boolean; created_at: string };
export default function AdminContactPage() {
  const [items, setItems] = useState<Message[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; void createClient().from("contact_messages").select("*").order("created_at", { ascending: false }).then(({ data }) => { if (active) { setItems((data ?? []) as Message[]); setLoading(false); } }); return () => { active = false; }; }, []);
  async function toggle(item: Message) { const { error } = await createClient().from("contact_messages").update({ is_read: !item.is_read }).eq("id", item.id); if (!error) setItems((all) => all.map((x) => x.id === item.id ? { ...x, is_read: !x.is_read } : x)); }
  async function remove(item: Message) { if (!window.confirm(`“${item.name}” tarafından gönderilen mesaj silinsin mi?`)) return; const { error } = await createClient().from("contact_messages").delete().eq("id", item.id); if (!error) setItems((all) => all.filter((x) => x.id !== item.id)); }
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-zinc-950">İletişim Formu</h1><p className="mt-1 text-sm text-slate-600">Web sitesi iletişim formundan gelen mesajları yönetin.</p></div>{loading ? <p className="flex items-center gap-2 py-12 text-slate-500"><LoaderCircle className="size-5 animate-spin" />Yükleniyor…</p> : items.length === 0 ? <p className="rounded-xl border border-dashed bg-white p-12 text-center text-sm text-slate-500">Henüz mesaj yok.</p> : <div className="space-y-3">{items.map((item) => <article key={item.id} className={`rounded-xl border bg-white p-5 shadow-sm ${item.is_read ? "border-zinc-200" : "border-red-200 ring-1 ring-red-100"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-bold text-zinc-950">{item.subject || "Konusuz mesaj"}</h2>{!item.is_read ? <span className="rounded-full bg-red-100 px-2 py-0.5 text-xs font-bold text-red-700">Yeni</span> : null}</div><p className="mt-1 text-sm text-slate-600">{item.name} · <a className="hover:underline" href={`mailto:${item.email}`}>{item.email}</a> · {formatTurkishDate(item.created_at)}</p></div><div className="flex gap-2"><button onClick={() => void toggle(item)} className="inline-flex items-center gap-1.5 rounded-md border px-3 py-2 text-xs font-semibold">{item.is_read ? <EyeOff className="size-4" /> : <Eye className="size-4" />}{item.is_read ? "Okunmadı yap" : "Okundu yap"}</button><button onClick={() => void remove(item)} className="inline-flex items-center gap-1.5 rounded-md border border-red-200 px-3 py-2 text-xs font-semibold text-red-700"><Trash2 className="size-4" />Sil</button></div></div><p className="mt-4 whitespace-pre-line text-sm leading-6 text-zinc-700">{item.message}</p></article>)}</div>}</div>;
}
