-- Intentionally a no-op. Historical substring-based deletion could remove real data.
-- Keep this migration number for existing databases. Test cleanup must be a separate,
-- reviewed operation targeting exact fixture IDs, never a production migration.
